export const THEME_CHANGE = "THEME_CHANGE";

export const STORE_IMAGE = "STORE_IMAGE";
export const CLEAR_IMAGE = "CLEAR_IMAGE";

export const SAVE_CASE = "SAVE_CASE";
export const CLEAR_CASE = "CLEAR_CASE";
export const EDIT_CASE = "EDIT_CASE";
export const DELETE_CASE = "DELETE_CASE";
export const UPDATE_USER_ID = 'UPDATE_USER_ID';
export const UPDATE_CASE_NUMBER = 'UPDATE_CASE_NUMBER';
export const UPDATE_CUSTOM_FIELD = 'UPDATE_CUSTOM_FIELD';
export const UPDATE_TYPE_AVAILABLE = 'UPDATE_TYPE_AVAILABLE';
export const UPDATE_TYPE_URL = 'UPDATE_TYPE_URL';

export const UPDATE_LANGUAGE = "UPDATE_LANGUAGE";

export const UPDATE_EMAIL = "UPDATE_EMAIL";

export const UPDATE_ICON = "UPDATE_ICON";
export const UPDATE_ICON_URL = "UPDATE_ICON_URL";

export const UPDATE_LOCATION = "UPDATE_LOCATION";
export const UPDATE_PERMISSION_STATUS = "UPDATE_PERMISSION_STATUS";

export const SAVE_ICON_PATH = "SAVE_ICON_PATH";

export const SAVE_CONFIG_TYPE = 'SAVE_CONFIG_TYPE';
export const SAVE_CUSTOM_CONFIG_URL = 'SAVE_CUSTOM_CONFIG_URL';
export const UPDATE_FORM_CONFIG = 'UPDATE_FORM_CONFIG';